package route

import (
	"fmt"
	"net"
	"os"
	"strings"

	"github.com/vishvananda/netlink"
)

const (
	ipForwardPath    = "/proc/sys/net/ipv4/ip_forward"
	sysctlConfigPath = "/etc/sysctl.d/99-cni-forward.conf"
)

// EnableIPForwarding enables IPv4 forwarding in the kernel
func EnableIPForwarding() error {
	return os.WriteFile(ipForwardPath, []byte("1"), 0644)
}

// DisableIPForwarding disables IPv4 forwarding
func DisableIPForwarding() error {
	return os.WriteFile(ipForwardPath, []byte("0"), 0644)
}

// IsIPForwardingEnabled checks if IP forwarding is currently enabled
func IsIPForwardingEnabled() (bool, error) {
	data, err := os.ReadFile(ipForwardPath)
	if err != nil {
		return false, fmt.Errorf("failed to read ip_forward: %w", err)
	}
	return strings.TrimSpace(string(data)) == "1", nil
}

// PersistIPForwarding creates a sysctl config file to make IP forwarding
// persistent across reboots
func PersistIPForwarding() error {
	content := `# CNI IP forwarding configuration
# Generated by poridhi-cni
net.ipv4.ip_forward = 1
`
	if err := os.WriteFile(sysctlConfigPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write sysctl config: %w", err)
	}
	return nil
}

// RemovePersistence removes the sysctl config file
func RemovePersistence() error {
	if err := os.Remove(sysctlConfigPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove sysctl config: %w", err)
	}
	return nil
}

// AddRoute adds a route to the routing table
func AddRoute(dst *net.IPNet, gw net.IP, linkName string) error {
	var link netlink.Link
	var err error

	if linkName != "" {
		link, err = netlink.LinkByName(linkName)
		if err != nil {
			return fmt.Errorf("failed to get link %s: %w", linkName, err)
		}
	}

	route := &netlink.Route{
		Dst: dst,
		Gw:  gw,
	}

	if link != nil {
		route.LinkIndex = link.Attrs().Index
	}

	if err := netlink.RouteAdd(route); err != nil {
		// Ignore "file exists" error - route already present
		if !strings.Contains(err.Error(), "file exists") {
			return fmt.Errorf("failed to add route: %w", err)
		}
	}

	return nil
}

// DeleteRoute removes a route from the routing table
func DeleteRoute(dst *net.IPNet) error {
	route := &netlink.Route{
		Dst: dst,
	}

	if err := netlink.RouteDel(route); err != nil {
		// Ignore "no such process" error - route already gone
		if !strings.Contains(err.Error(), "no such process") {
			return fmt.Errorf("failed to delete route: %w", err)
		}
	}

	return nil
}

// GetRoutes returns all routes for a specific interface
func GetRoutes(linkName string) ([]netlink.Route, error) {
	link, err := netlink.LinkByName(linkName)
	if err != nil {
		return nil, fmt.Errorf("failed to get link: %w", err)
	}

	routes, err := netlink.RouteList(link, netlink.FAMILY_V4)
	if err != nil {
		return nil, fmt.Errorf("failed to list routes: %w", err)
	}

	return routes, nil
}

// RouteInfo represents route information in a friendly format
type RouteInfo struct {
	Destination string
	Gateway     string
	Device      string
	Scope       string
}

// GetRouteTable returns the full IPv4 routing table
func GetRouteTable() ([]RouteInfo, error) {
	routes, err := netlink.RouteList(nil, netlink.FAMILY_V4)
	if err != nil {
		return nil, fmt.Errorf("failed to list routes: %w", err)
	}

	var result []RouteInfo
	for _, r := range routes {
		info := RouteInfo{
			Scope: r.Scope.String(),
		}

		if r.Dst != nil {
			info.Destination = r.Dst.String()
		} else {
			info.Destination = "default"
		}

		if r.Gw != nil {
			info.Gateway = r.Gw.String()
		}

		if r.LinkIndex > 0 {
			link, err := netlink.LinkByIndex(r.LinkIndex)
			if err == nil {
				info.Device = link.Attrs().Name
			}
		}

		result = append(result, info)
	}

	return result, nil
}

// AddDefaultRoute adds a default route (0.0.0.0/0) via the specified gateway
func AddDefaultRoute(gw net.IP, linkName string) error {
	_, defaultNet, _ := net.ParseCIDR("0.0.0.0/0")
	return AddRoute(defaultNet, gw, linkName)
}

